Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# hide this code
# did it in graphviz so we can play around
# maybe the final version should be in inkscape/powerpoint?

import graphviz
g = graphviz.Digraph()

g.attr(rankdir='LR', size='6,5')
g.attr('node', shape='doublecircle')
g.node('Phenomenon')

g.attr('node', shape='oval')
g.node('Measurement')
g.node('Sample')
g.node('Data Generating Process')


g.edge('Phenomenon','Data Generating Process')
g.edge('Measurement','Data Generating Process')

g.edge('Data Generating Process','Sample')
g.edge('Sample','Data')

g.node('Data', shape='star')
#g.edge('Data','Phenomenon', label='Inference')

g
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/tmp/ipykernel_2632/583374093.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;31m# maybe the final version should be in inkscape/powerpoint?[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mimport[0m [0mgraphviz[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0mg[0m [0;34m=[0m [0mgraphviz[0m[0;34m.[0m[0mDigraph[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'graphviz'
ModuleNotFoundError: No module named 'graphviz'

